name: deploy on push to master

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          cargo install cargo-get

      - name: Get current version
        run: |
          VERSION=$(cargo get package.version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push versions
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_BRANCH_NAME }}/webfs:latest,${{ vars.DOCKERHUB_BRANCH_NAME }}/webfs:${{ env.VERSION }}